#index:
#    path: /
#    controller: App\Controller\DefaultController::index
contorllers:
    resource: '../src/Controller'
    type: annotation
    prefix: /api

api_login_check:
    path: /api/login_check